server:
  port: 8888
  servlet:
    context-path: /community
spring:
  thymeleaf:
    cache: false
#datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.newcoder.community.entity
  configuration:
    useGeneratedKeys: true
    mapUnderscoreToCamelCase: true
#logger
#logging:
#  level:
#    root: info
#    com.newcoder.community: debug
#  file: D:\\community\\log\\community.log

